// Update variables below according to your needs
aws_region = "us-east-2"
aws_az = "us-east-2a"
aws_key_name = "mtecer"
instance_type = "t2.micro"
instance_name = "web"
vpc_cidr = "10.10.0.0/16"
public_cidr = "10.10.1.0/16"
server_port = "80"
count = "1"
